---
title: "angelo1"
author: "StephanLewandowsky"
date: "2019-09-24"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

The analyses are available at https://stephanlewandowsky.github.io/angelo/. 

```{r echo=FALSE, warning=FALSE, message=FALSE, results="hide"}
rm(list=ls())
library(lattice)
library(stargazer)
library(tidyverse)
library(lme4)
library(lavaan)
library(semPlot)
library(semTools)
library(RColorBrewer)
library(gridExtra)
library(stringr)
library(Hmisc)
library(reshape2)
library(psych)
library(scales)
library(summarytools) #contains descr()
library(workflowr)

source("analysis/funcs.r")

revscore <- function (x,cluster) {  #this reverse scores a scale for items of reversed polarity
  return ((likscaleupper[cluster]+1)-x)            
}

#define working directories
inputdir <- "data"

##--- Begin by reading data and variable names -----------------------------------------------------------------------
angelo1 <- read.csv(paste(inputdir,"Study 1 - Data Matrix (Complete).csv",sep="/"),header=TRUE,row.names=NULL) 
```

## Summary statistics
```{r summary, echo=FALSE}
table(angelo1$Sex)
prop.table(table(angelo1$Sex))

descr(angelo1$Age)

table(angelo1$Education)
prop.table(table(angelo1$Education))

descr(select(angelo1,starts_with("Polit")))

itemclusters <- c("R.PBS", "IAS.R.PBS", "GCBS", "IAS.GCBS", "PSEUDO", "IAS.PSEUDO")
```

## Participants who pressed the same key for all items in a cluster (0: no cluster, >=1: number of clusters)
```{r keyhitters, echo=FALSE}
# identify keyhitters before reverse-scoring
neutral <- 0 #if set to zero, any sequence of identical keys is eliminated. If set to 4, only non-neutral responses are dropped
keyhitters <- NULL
for (cluster in itemclusters) {
   keyhitters <- cbind(keyhitters, angelo1 %>% select(starts_with(cluster)) %>% 
                      apply(.,1,FUN=function(x) ifelse((var(x)==0 & mean(x)!=neutral),1,0)) )
 }
table(rowSums(keyhitters))


#do reverse scoring
likscaleupper <- c(7,4,5,4,5,4)
names(likscaleupper) <- itemclusters
angelo2 <- select(angelo1,1:6) #grab first bit, then add columns
for (cluster in itemclusters) {
   angelo2 <- cbind(angelo2, angelo1 %>% select(starts_with(cluster)) %>% mutate_at(vars(contains("..R")),revscore,cluster)) 
}
angelo2 <- cbind(angelo2,angelo1$SIN.B)
```

```{r corrs, echo=FALSE, results="hide"}
# compute pairwise correlations within each cluster
for (cluster in itemclusters) {
  angelo2 %>% select(starts_with(cluster)) %>% cor(use="complete.obs") %>% print
}

```


## Compute measurement models for each cluster
```{r singinds, echo=FALSE}

  expl <- angelo2 %>% select(starts_with( "R.PBS")) %>% select(-c(R.PBS.23..R.,  R.PBS.20 ))

  vars <- angelo2 %>% select(starts_with( "R.PBS")) %>% select(-c(R.PBS.23..R.,  R.PBS.20 )) %>% names
  fmmod <- c("fm =~ ",paste(vars,collapse=" + "),"R.PBS.8 ~~ R.PBS.22","R.PBS.2 ~~  R.PBS.9","R.PBS.1 ~~ R.PBS.15","R.PBS.11 ~~ R.PBS.18","R.PBS.6 ~~ R.PBS.13")
  invisible(fmgof<-fitMM (fmmod,angelo2))
  
  vars <- angelo2 %>% select(starts_with( "IAS.R.PBS")) %>%  names
  fmmod <- c("fm =~ ",paste(vars,collapse=" + ")," IAS.R.PBS.4..R. ~~ IAS.R.PBS.5..R.")
  invisible(fmgof<-fitMM (fmmod,angelo2))

  vars <- angelo2 %>% select(starts_with("GCBS")) %>%  names
  fmmod <- c("fm =~ ",paste(vars,collapse=" + "),"GCBS.7 ~~ GCBS.8","GCBS.1 ~~ GCBS.2")
  invisible(fmgof<-fitMM (fmmod,angelo2))

  vars <- angelo2 %>% select(starts_with("IAS.GCBS")) %>%  names
  fmmod <- c("fm =~ ",paste(vars,collapse=" + "),"IAS.GCBS.2 ~~     IAS.GCBS.3","IAS.GCBS.4..R. ~~ IAS.GCBS.5..R.")
  invisible(fmgof<-fitMM (fmmod,angelo2))

  vars <- angelo2 %>% select(starts_with("PSEUDO")) %>% select(-c(PSEUDO.19, PSEUDO.4..R.)) %>% names
  fmmod <- c("fm =~ ",paste(vars,collapse=" + "),"PSEUDO.1 ~~  PSEUDO.2","PSEUDO.24..R. ~~ PSEUDO.29")
  invisible(fmgof<-fitMM (fmmod,angelo2))

  vars <- angelo2 %>% select(starts_with("IAS.PSEUDO")) %>% names
  fmmod <- c("fm =~ ",paste(vars,collapse=" + "),"IAS.PSEUDO.4..R. ~~ IAS.PSEUDO.5..R.","IAS.PSEUDO.1..R. ~~ IAS.PSEUDO.5..R.")
  invisible(fmgof<-fitMM (fmmod,angelo2))



```


## Correlations among composites
```{r composites, echo=FALSE}

angelocomps <- NULL
for (cluster in itemclusters) {
    angelocomps <- cbind(angelocomps, angelo2 %>% select(starts_with(cluster)) %>% apply(.,1,mean,na.rm=TRUE))
}
angelocomps <- as.data.frame(angelocomps)
names(angelocomps) <- itemclusters
angelocomps <- cbind(select(angelo1,1:6), angelocomps)

cor(angelocomps %>% select(-c(1:6)))

```  
